DATA:
  IMG_SIZE: 448

#TRAIN:
#  ACCUMULATION_STEPS: 2 # For Gradient Accumulation

MODEL:
  TYPE: swin
  NAME: MTLprompt_tiny_448_scale4
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7

  FUSION_HEAD: "hrnet"  # default

  PER_TASK_DOWNSAMPLER: True
  DECODER_DOWNSAMPLER: True

  MTLPROMPT:
    ENABLED: True
    DECODER_TYPE: "baseline" # "share | sep_last | sep | firstblocksep | baseline"
    PROMPT:
      PROMPT_DROPOUT: 0
      SHARED:
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 10   #
      SPATIAL:
        ENCODER: True # "Use task-specific prompt in encoder stage's last block (Similar to baseline)"
        ENABLED: False
        METHOD: "prepend" # prepend | low-rank
        TAILOR: "MLP" # TODO "INIT | MLP | FACT"
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 10  #  TODO :
      CHANNEL:
        ENABLED: False
        TAILOR: "MLP" # TODO "INIT | MLP | FACT"
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 2
        CHAN_N_HEADS: 16
        CHAN_EMBED_DIM : 256
#    MODULATION:  # MODULATION FOR TASK-SPECIFIC FEATURES
#      ENABLE : TRUE
#      TYPE : "element-wise" # "element-wise | FiLM"

    FINAL_EMBED_DIM : 96

    FREEZE_PRETRAINED: True

  DECODER_HEAD:
    semseg: hrnet
    normals: hrnet
    sal: hrnet
    human_parts: hrnet
    edge: hrnet
    depth: hrnet












