DATA:
  IMG_SIZE: 448

#TRAIN:
#  ACCUMULATION_STEPS: 2 # For Gradient Accumulation

MODEL:
  TYPE: swin
  NAME: MTLprompt_tiny_448_scale4
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7

  FUSION_HEAD: "hrnet"  # default

  PER_TASK_DOWNSAMPLER: True
  DECODER_DOWNSAMPLER: True

  MTLPROMPT:
    ENABLED: True
    DECODER_TYPE: "baseline" # " baseline "
    PROMPT:
      PROMPT_DROPOUT: 0
      SHARED:
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 10   #
        METHOD: "prepend"
      SPATIAL:
        ENABLED: True # "Use task-specific prompt in encoder stage's last block (Similar to baseline)"
        METHOD: "prepend" # prepend | low-rank
        TAILOR: "MLP" # TODO "INIT | MLP | FACT"
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 10  #  TODO :

    DOWNSAMPLER_ENABLED: False
    FINAL_EMBED_DIM : 96
    FREEZE_PRETRAINED: True

  DECODER_HEAD:
    semseg: hrnet
    normals: hrnet
    sal: hrnet
    human_parts: hrnet
    edge: hrnet
    depth: hrnet












