DATA:
  IMG_SIZE: 448

TRAIN:
  ACCUMULATION_STEPS: 4 # For Gradient Accumulation

MODEL:
  TYPE: swin
  NAME: MTLprompt_tiny_448_scale4
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7

  FUSION_HEAD: "hrnet"  # default

  PER_TASK_DOWNSAMPLER: False
  DECODER_DOWNSAMPLER: False

  MTLPROMPT:
    ENABLED: True
    DECODER_TYPE: "firstblocksep" # "share | sep_last | sep | firstblocksep"
    PROMPT:
      PROMPT_DROPOUT: 0
      SHARED:
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 12   #
      SPATIAL:
        ENABLED: True
        TAILOR: "MLP" # TODO "INIT | MLP | FACT"
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 12  #  TODO :
      CHANNEL:
        ENABLED: False
        TAILOR: "MLP" # TODO "INIT | MLP | FACT"
        TYPE: SHALLOW # " DEEP | SHALLOW "
        LEN: 2
        CHAN_N_HEADS: 16
        CHAN_EMBED_DIM : 256

    FINAL_EMBED_DIM : 96

    FREEZE_PRETRAINED: True


  MTLORA:
    ENABLED: False
    R: [16, 16, 16, 16]
    SHARED_SCALE: [4.0]
    TASK_SCALE: [4.0]
    DROPOUT: [0.05, 0.05, 0.05, 0.05]
    TRAINABLE_SCALE_SHARED: False
    TRAINABLE_SCALE_PER_TASK: False
    INTERMEDIATE_SPECIALIZATION: False
    FREEZE_PRETRAINED: True
    SPLIT_QKV: False
    QKV_ENABLED: True
    PROJ_ENABLED: True
    FC1_ENABLED: True
    FC2_ENABLED: True
    DOWNSAMPLER_ENABLED: False
    R_PER_TASK:
      semseg: [4]
      normals: [4]
      sal: [4]
      human_parts: [4]
      edge: [4]
      depth: [4]
      shared: [16]
  DECODER_HEAD:
    semseg: 3x3conv
    normals: 3x3conv
    sal: 3x3conv
    human_parts: 3x3conv
    edge: 3x3conv
    depth: 3x3conv











